services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: mymongodb
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
  app:
    build: .
    container_name: springboot-app
    restart: unless-stopped
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongoadmin:secret@mongodb:27017/mymongodb
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongo-data:
  mongo-config: